name: tugas3mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  geolocator: ^10.0.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.12
  decimal: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

##flutter:
 ## assets:
 ##  - assets/logo.png

apiVersion: configmanagement.gke.io/v1
kind: ClusterSelector
metadata:
  name: selector-env-prod
spec:
  selector:
    matchLabels:
      environment: prod
